version: "3"
services:
  app.test:
    build: .
    image: dectron2.1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
     - ".:/code"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
