version: "3"
services:
  app.test:
    build: .
    image: dectron2.12
    ports:
      - "${APP_PORT:-5000}:5000"
      - "${APP_PORTHTTPS:-443}:443"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
     - ".:/code"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
